!!python/object:processing.parameters.MapExtractionParameters

# Visibility
isovist_height:
- 1.5
- 1.8
isovist_range: 3
isovist_spacing: 0.5
isovist_subsample: 1

# Markov Clustering
max_inflation: 2
min_inflation: 1.1
weight_threshold: 0.4

# Room segmentation
min_voxels: 512

# Traversable manifold
kernel_scale: 0.05

# Resolution
leaf_voxel_size: 0.1
traversability_lod: 0
segmentation_lod: 0
