!!python/object:processing.map_extract.MapExtractionParameters

# Visibility
isovist_height: !!python/tuple
- 1.5
- 1.8
isovist_range: 5
isovist_spacing: 0.5
isovist_subsample: 1

# Markov Clustering
max_inflation: 2
min_inflation: 1.1
weight_threshold: 0.5

# Room segmentation
min_voxels: 100

# Traversable manifold
kernel_scale: 0.05

# Resolution
leaf_voxel_size: 0.05
traversability_lod: 0
segmentation_lod: 2
